Feature 1712 upgrade to 300
NCEAS/metacat pull request #1811
Opened 2024-02-24 02:03 UTC by taojing2002

2024-02-27 23:15 UTC, artntek requested changes

2024-02-27 23:15 UTC, artntek commented on src/edu/ucsb/nceas/metacat/admin/upgrade/solr/SolrConfigUpgrader.java
> +            throw new PropertyNotFoundException("SolrConfigUpdator.Constructor - "
SolrConfigUpdator is wrong class name. See earlier comment about removing class & method names from log messages

2024-02-27 23:15 UTC, artntek commented on src/edu/ucsb/nceas/metacat/admin/upgrade/solr/SolrJvmVersionFinder.java
> +            return new String(result, StandardCharsets.UTF_8.name());
`.name()` is unnecessary

2024-02-27 23:15 UTC, artntek commented on src/edu/ucsb/nceas/metacat/admin/upgrade/solr/SolrJvmVersionFinder.java
> +    private DocumentBuilderFactory factory;
doesn't need to be a global variable

2024-02-29 18:32 UTC, taojing2002 commented on src/edu/ucsb/nceas/metacat/admin/DBAdmin.java
> +        if (metaCatVersion != null) {
Just in case if it is null. I like the defensive style code :)

2024-02-29 19:26 UTC, taojing2002 commented on src/edu/ucsb/nceas/metacat/admin/upgrade/solr/SolrConfigUpgrader.java
> +                            logMetacat.warn("SolrConfigUpgrader.upgrade - " + error1);
Just in case.

2024-02-29 19:26 UTC, taojing2002 commented on src/edu/ucsb/nceas/metacat/admin/upgrade/solr/SolrConfigUpgrader.java
>                          if(checkSum != null) {
Just in case.

2024-02-29 20:25 UTC, taojing2002 commented on src/edu/ucsb/nceas/metacat/admin/SolrAdmin.java
> +    public void configureSolr(HttpServletRequest request,
It is hard understanding.

2024-02-29 22:03 UTC, artntek commented on src/edu/ucsb/nceas/metacat/admin/DBAdmin.java
> +        PrerequisiteChecker300 checker = new PrerequisiteChecker300();
ok

2024-02-29 22:06 UTC, artntek commented on src/edu/ucsb/nceas/metacat/admin/SolrAdmin.java
> +    public void configureSolr(HttpServletRequest request,
that is my point - such a huge and nested method is very hard to understand

2024-02-29 22:09 UTC, artntek commented on src/edu/ucsb/nceas/metacat/admin/upgrade/solr/SolrConfigUpgrader.java
> +                            logMetacat.warn("SolrConfigUpgrader.upgrade - " + error1);
just in case the laws of physics ever change? 🤣

2024-02-29 22:49 UTC, taojing2002 commented
Software behaviors are much different to the laws of physics  🤣
Before we saw lots of null pointer exceptions, so I adopted the defensive
styles 😀

On Thu, Feb 29, 2024 at 2:09 PM Matthew B ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/edu/ucsb/nceas/metacat/admin/upgrade/solr/SolrConfigUpgrader.java
> <https://github.com/NCEAS/metacat/pull/1811#discussion_r1508251059>:
>
> > +                            File backupFile =
> +                                    new File(getFileName(solrHomePath + CONFIGFILERELATIVEPATH));
>                              FileUtils.copyFile(configFile, backupFile);
>                              //overwrite the solr.config file
>                              FileUtils.copyFile(metacatIndexConfigFile, configFile);
> -                            throw new SolrSchemaModificationException(error1);
> +                            logMetacat.warn("SolrConfigUpgrader.upgrade - " + error1);
>
> just in case the laws of physics ever change? 🤣
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NCEAS/metacat/pull/1811#discussion_r1508251059>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB5QQDFCFJ4IBAKBJIV5ZWDYV6TKRAVCNFSM6AAAAABDXTX5WWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMBZHE3DGOBXGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-01 00:37 UTC, taojing2002 commented on src/edu/ucsb/nceas/metacat/admin/SolrAdmin.java
> +                 File envScriptFile = new File(envScriptPath);
Yeah. But since we don't reuse this part, do you think we should move them to another method?

2024-03-04 17:32 UTC, artntek commented on metacat-common/src/test/java/edu/ucsb/nceas/metacat/common/query/SolrQueryServiceControllerTest.java
> +        assertTrue("The number of index schema fields should be " + targetSize + " rather than "
why not `assertEquals`? (That would automatically print out the `Expected` and `Actual` values if they differ, without you needing to concatenate them into the string message.) i.e.:

```java
assertEquals("The number of index schema fields is incorrect", targetSize, fields.size());
```

2024-03-04 17:32 UTC, artntek commented on metacat-common/src/test/java/edu/ucsb/nceas/metacat/common/query/SolrQueryServiceControllerTest.java
> +        assertTrue(fields != null);
`AssertNotNull()` is more informative when it fails

2024-03-04 17:32 UTC, artntek commented on src/edu/ucsb/nceas/metacat/admin/SolrAdmin.java
> +                 File envScriptFile = new File(envScriptPath);
you're right. I was thinking about readability rather than re-use, but this is the only functionality in the current method 🤣. Please ignore

2024-03-04 20:01 UTC, artntek reviewed
I still see a couple of unanswered comments:
https://github.com/NCEAS/metacat/pull/1811/#discussion_r1505024251
https://github.com/NCEAS/metacat/pull/1811/#discussion_r1505014270

2024-03-04 21:27 UTC, artntek approved these changes

2024-03-04 21:28 UTC, merged