Feature 1642 action transaction
NCEAS/metacat pull request #1823
Opened 2024-03-13 18:28 UTC by taojing2002

Please double check two items in MetacatHandler.save:

- No accidental overwriting of the existing objects
- No accidental deleting of the existing objects

2024-03-20 23:51 UTC, artntek requested changes
Phew - that was intense 😅 

Please check all your tests and rename the ones that rely on database/metacat instance to `*IT`, if I missed any.

Thanks!

2024-03-20 23:51 UTC, artntek commented on test/edu/ucsb/nceas/metacat/MetacatHandlerTest.java
> +public class MetacatHandlerTest {
this is an integration test that relies on the database - can we rename it to `MetacatHandlerIT`?

2024-03-20 23:51 UTC, artntek commented on test/edu/ucsb/nceas/metacat/MetacatHandlerTest.java
> +    public void testSaveMethodWithMock() throws Exception {
The console output for this test method starts with:

```log
LeanTestUtils: 'test.printdebug' is TRUE
LeanTestUtils: PropertyService initialized in UNIT_TEST mode; using default properties from lib/metacat.properties overlaid with configurable properties from test/test.properties
LeanTestUtils: PropertyService initialized in LIVE_TEST mode; using default properties from /opt/local/share/java/tomcat/webapps/metacat/WEB-INF/metacat.properties overlaid with configurable properties from /var/metacat/config/metacat-site.properties
```

The call to initialize `UNIT_TEST` is set up in your `setUp()` method, but I can't see where you are making a call to initialize `LIVE_TEST` in this method. I'm guessing it is not intentional?

2024-03-20 23:51 UTC, artntek commented on test/edu/ucsb/nceas/metacat/MetacatHandlerTest.java
### Comment 3
It's lovely to see such rigorous testing. On the other hand, it's really difficult to follow what is actually happening, when test methods are hundreds of lines long 😞 Consequently, I have not gone through all these at a fine-grained level. I'd encourage all of us to try to keep test methods very small for newly-created tests

2024-03-20 23:51 UTC, artntek commented on test/edu/ucsb/nceas/metacat/dataone/CNodeServiceTest.java
rename to CNodeServiceIT?

2024-03-20 23:51 UTC, artntek commented on test/edu/ucsb/nceas/metacat/dataone/MNodeServiceIT.java
see comments about `assertTrue` vs. `assertEquals` on MetacatHandlerTest - same applies to many of the ones added below

2024-03-20 23:51 UTC, artntek commented on test/edu/ucsb/nceas/metacat/MetacatHandlerTest.java
> +    public void testSaveMethodWithMock() throws Exception {
found it - line 1126. `D1NodeServiceTest` extends `MCTestCase`, which does this `LIVE_TEST` init.

2024-03-20 23:51 UTC, artntek commented on test/edu/ucsb/nceas/metacat/systemmetadata/SystemMetadataValidatorTest.java
> +public class SystemMetadataValidatorTest {
`SystemMetadataValidatorIT`?

2024-03-20 23:51 UTC, artntek commented on test/edu/ucsb/nceas/metacattest/NonAsciiCharacterTest.java
> +public class NonAsciiCharacterTest {
`NonAsciiCharacterIT`?

2024-03-21 03:22 UTC, taojing2002 commented on src/edu/ucsb/nceas/metacat/MetacatHandler.java
> +     *                It will be ignore in the update action.
It should be ignored when the request is an INSERT action.

2024-03-21 03:35 UTC, taojing2002 commented on src/edu/ucsb/nceas/metacat/MetacatHandler.java
> +                            logMetacat.info(edu.ucsb.nceas.metacat.common.Settings.PERFORMANCELOG
There were two Settings classes were imported. So I had to use the full name. But it is only one so we can import it.

2024-03-21 06:43 UTC, taojing2002 commented on test/edu/ucsb/nceas/metacat/dataone/MNodeServiceIT.java
I didn't trust the `assertEquals` for the string comparisons, so I used str.equal(str2).

2024-03-21 21:55 UTC, taojing2002 commented on src/edu/ucsb/nceas/metacat/DocumentImpl.java
> +            String query = "SELECT * FROM xml_documents WHERE docid = ? and rev = ?";
Now it selects the doctype from here and also the method of `getDocTypeFromDB()` was deleted.

2024-03-21 22:33 UTC, artntek reviewed
have reviewed all changes up to 8832504727beb32d51267f7df338da6591d7cd8a

2024-03-21 23:55 UTC, taojing2002 commented on src/edu/ucsb/nceas/metacat/dataone/D1NodeService.java
>          throws InvalidToken, ServiceFailure, NotAuthorized, NotFound, NotImplemented {
The param does need. So I added the parameter in the `DocumentImpl.archive` method as well.

2024-03-22 03:04 UTC, artntek approved these changes

2024-03-22 03:10 UTC, artntek approved these changes

2024-03-22 03:10 UTC, merged