Bugfix 1855 replica different datemodified
NCEAS/metacat pull request #1860
Opened 2024-04-02 05:21 UTC by taojing2002

2024-04-02 20:08 UTC, artntek requested changes

2024-04-02 20:08 UTC, artntek commented on test/edu/ucsb/nceas/metacat/dataone/MNodeServiceIT.java
> +                        + "</principal><permission>read</permission></allow></access>" + "<dataset"
unnecessary concat: `</access>" + "<dataset`

Also consider using java 17 block quotes for this and also line 780, 836, & 857, for better readability?

2024-04-02 23:12 UTC, taojing2002 commented on src/edu/ucsb/nceas/metacat/dataone/D1NodeService.java
> +     * @param sysMetaCheck - if Metacat needs to check the version of the coming system metadata
Y

2024-04-02 23:43 UTC, taojing2002 commented on test/edu/ucsb/nceas/metacat/DocumentImplIT.java
Good catch! Actually in the MNodeServiceIT class, there is a test indirectly to test `UNCHECKED` in this method. Anyway, I would like to add one.

2024-04-04 01:04 UTC, artntek approved these changes

2024-04-04 01:07 UTC, merged